name: Test App

on:
  push:

jobs:
  test_python:
    runs-on: ubuntu-26.04-arm
    container:
      image: nikolaik/python-nodejs:python3.14-nodejs26-slim
      options: --user 1000:1000
    
    steps:
    - uses: actions/checkout@v6
    - name: Install Pip Packages
      run: |
        pip3 install -r requirements.txt
        pip3 install -e .
    - name: Run Tests
      run: |
        python3 -m coverage run -m pytest
        python3 -m coverage html
    - name: Upload code coverage results
      uses: actions/upload-artifact@v7
      with:
        name: code-coverage-report-python-test
        path: htmlcov
        retention-days: 7